version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "3001:3000"
    volumes:
    - /app/node_modules
    - .:/app # current folder outside the container to /app inside the container
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
    - /app/node_modules
    - .:/app # current folder outside the container to /app inside the container
    command: ["npm", "run", "test"] # override the default command